# The secret key used for encryption by Flask.
# This should be changed for every new instance of the server that is set up.
secret-key: 'c\xcc\xc6\xee9\x81tn\xd0Lm\xd2X\x0c\x9d\x05\x1a\xd606\x95\x92\xb3\xc1'
