name: whats_your_bread_type
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.7.7
  - pyyaml==5.3.1
  - flask==1.1.1
  - flask-sqlalchemy==2.4.1
  - flask-login==0.4.1
  - flask-cli==0.4.0
